const mongoose = require("mongoose");
const Student = require("./models/Student"); // Assuming your schema is in models/Student.js

mongoose
  .connect(
    "mongodb+srv://ayorbami17:student123@students.vao0r.mongodb.net/students?retryWrites=true&w=majority",
    {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    }
  )
  .then(() => {
    console.log("MongoDB connected");

    // Student data
    const studentsData = [
      {
        ID: 1,
        name: "John Doe",
        course: "Computer Science",
        email: "johndoe@example.com",
        phone: "+1-202-555-0111",
        createdAt: new Date("2024-01-15"),
        action: "Edit/Delete",
      },
      {
        ID: 2,
        name: "Jane Smith",
        course: "Mechanical Engineering",
        email: "janesmith@example.com",
        phone: "+1-202-555-0112",
        createdAt: new Date("2024-01-16"),
        action: "Edit/Delete",
      },
      {
        ID: 3,
        Name: "Alice Johnson",
        Course: "Electrical Engineering",
        Email: "alicejohnson@example.com",
        Phone: "+1-202-555-0113",
        Created_At: "2024-01-17",
        Action: "Edit/Delete",
      },
      {
        ID: 4,
        Name: "Bob Williams",
        Course: "Business Administration",
        Email: "bobwilliams@example.com",
        Phone: "+1-202-555-0114",
        Created_At: "2024-01-18",
        Action: "Edit/Delete",
      },
      {
        ID: 5,
        Name: "Emily Brown",
        Course: "Civil Engineering",
        Email: "emilybrown@example.com",
        Phone: "+1-202-555-0115",
        Created_At: "2024-01-19",
        Action: "Edit/Delete",
      },
      {
        ID: 6,
        Name: "David Miller",
        Course: "Computer Science",
        Email: "davidmiller@example.com",
        Phone: "+1-202-555-0116",
        Created_At: "2024-01-20",
        Action: "Edit/Delete",
      },
      {
        ID: 7,
        Name: "Sophia Martinez",
        Course: "Biology",
        Email: "sophiamartinez@example.com",
        Phone: "+1-202-555-0117",
        Created_At: "2024-01-21",
        Action: "Edit/Delete",
      },
      {
        ID: 8,
        Name: "James Taylor",
        Course: "Physics",
        Email: "jamestaylor@example.com",
        Phone: "+1-202-555-0118",
        Created_At: "2024-01-22",
        Action: "Edit/Delete",
      },
      {
        ID: 9,
        Name: "Olivia Anderson",
        Course: "Mathematics",
        Email: "oliviaanderson@example.com",
        Phone: "+1-202-555-0119",
        Created_At: "2024-01-23",
        Action: "Edit/Delete",
      },
      {
        ID: 10,
        Name: "Liam Thomas",
        Course: "Chemistry",
        Email: "liamthomas@example.com",
        Phone: "+1-202-555-0120",
        Created_At: "2024-01-24",
        Action: "Edit/Delete",
      },
      {
        ID: 11,
        Name: "Emma White",
        Course: "Computer Science",
        Email: "emmawhite@example.com",
        Phone: "+1-202-555-0121",
        Created_At: "2024-01-25",
        Action: "Edit/Delete",
      },
      {
        ID: 12,
        Name: "Michael Harris",
        Course: "Psychology",
        Email: "michaelharris@example.com",
        Phone: "+1-202-555-0122",
        Created_At: "2024-01-26",
        Action: "Edit/Delete",
      },
      {
        ID: 13,
        Name: "Isabella Clark",
        Course: "Sociology",
        Email: "isabellaclark@example.com",
        Phone: "+1-202-555-0123",
        Created_At: "2024-01-27",
        Action: "Edit/Delete",
      },
      {
        ID: 14,
        Name: "William Lewis",
        Course: "History",
        Email: "williamlewis@example.com",
        Phone: "+1-202-555-0124",
        Created_At: "2024-01-28",
        Action: "Edit/Delete",
      },
      {
        ID: 15,
        Name: "Ava Robinson",
        Course: "Political Science",
        Email: "avarobinson@example.com",
        Phone: "+1-202-555-0125",
        Created_At: "2024-01-29",
        Action: "Edit/Delete",
      },
      {
        ID: 16,
        Name: "Elijah Walker",
        Course: "Philosophy",
        Email: "elijahwalker@example.com",
        Phone: "+1-202-555-0126",
        Created_At: "2024-01-30",
        Action: "Edit/Delete",
      },
      {
        ID: 17,
        Name: "Mia Hall",
        Course: "Art History",
        Email: "miahall@example.com",
        Phone: "+1-202-555-0127",
        Created_At: "2024-01-31",
        Action: "Edit/Delete",
      },
      {
        ID: 18,
        Name: "Alexander Young",
        Course: "Economics",
        Email: "alexanderyoung@example.com",
        Phone: "+1-202-555-0128",
        Created_At: "2024-02-01",
        Action: "Edit/Delete",
      },
      {
        ID: 19,
        Name: "Charlotte King",
        Course: "Literature",
        Email: "charlotteking@example.com",
        Phone: "+1-202-555-0129",
        Created_At: "2024-02-02",
        Action: "Edit/Delete",
      },
      {
        ID: 20,
        Name: "Henry Scott",
        Course: "Environmental Science",
        Email: "henryscott@example.com",
        Phone: "+1-202-555-0130",
        Created_At: "2024-02-03",
        Action: "Edit/Delete",
      },
      {
        ID: 21,
        Name: "Amelia Green",
        Course: "Anthropology",
        Email: "ameliagreen@example.com",
        Phone: "+1-202-555-0131",
        Created_At: "2024-02-04",
        Action: "Edit/Delete",
      },
      {
        ID: 22,
        Name: "Sebastian Baker",
        Course: "Engineering",
        Email: "sebastianbaker@example.com",
        Phone: "+1-202-555-0132",
        Created_At: "2024-02-05",
        Action: "Edit/Delete",
      },
      {
        ID: 23,
        Name: "Harper Adams",
        Course: "Law",
        Email: "harperadams@example.com",
        Phone: "+1-202-555-0133",
        Created_At: "2024-02-06",
        Action: "Edit/Delete",
      },
      {
        ID: 24,
        Name: "Lucas Parker",
        Course: "Medicine",
        Email: "lucasparker@example.com",
        Phone: "+1-202-555-0134",
        Created_At: "2024-02-07",
        Action: "Edit/Delete",
      },
      {
        ID: 25,
        Name: "Evelyn Campbell",
        Course: "Nursing",
        Email: "evelyncampbell@example.com",
        Phone: "+1-202-555-0135",
        Created_At: "2024-02-08",
        Action: "Edit/Delete",
      },
      {
        ID: 26,
        Name: "Mason Edwards",
        Course: "Journalism",
        Email: "masonedwards@example.com",
        Phone: "+1-202-555-0136",
        Created_At: "2024-02-09",
        Action: "Edit/Delete",
      },
      {
        ID: 27,
        Name: "Abigail Torres",
        Course: "Music",
        Email: "abigailtorres@example.com",
        Phone: "+1-202-555-0137",
        Created_At: "2024-02-10",
        Action: "Edit/Delete",
      },
      {
        ID: 28,
        Name: "Daniel Brooks",
        Course: "Architecture",
        Email: "danielbrooks@example.com",
        Phone: "+1-202-555-0138",
        Created_At: "2024-02-11",
        Action: "Edit/Delete",
      },
      {
        ID: 29,
        Name: "Chloe Gray",
        Course: "Theater Arts",
        Email: "chloegray@example.com",
        Phone: "+1-202-555-0139",
        Created_At: "2024-02-12",
        Action: "Edit/Delete",
      },
      {
        ID: 30,
        Name: "Jack Ramirez",
        Course: "Graphic Design",
        Email: "jackramirez@example.com",
        Phone: "+1-202-555-0140",
        Created_At: "2024-02-13",
        Action: "Edit/Delete",
      },
      // Add the rest of the student data here
    ];

    // Insert data into the collection
    Student.insertMany(studentsData)
      .then(() => {
        console.log("Data inserted");
        mongoose.connection.close();
      })
      .catch((err) => console.log(err));
  })
  .catch((err) => console.log(err));
